#!/bin/python3 

# Package imports
import sys

# Local imports
import instructionFuncs

#Mhmm I think i should be able to add comments into the assembly code that should not be to difficult i think
#The comments are now a thing in the assembly! Yipzerz

#When this assembler actually is doing something rather then doing a small bit I might want to think about making something like an argument parser (same for the virtual machine btw)

#I do kinda want an option to specify the name of the output file that is generated by this assembler
#I do kinda need to start writing my own argument parser am I not...

# Next to the fact that I am taking it upon myself to write argument parsers for both python and cpp I will also change this assembler quite a bit
# I am going to make this assembler (probably) two stage one to take out all the comments and give me general information and replace macro's and labels
# And the other to actually replace everything with their right values

def readFile(fileName):

    if fileName.find(".mav") == -1:
        print("Your file does not have the correct file extension!")
        exit(-1)

    try:
        file = open(fileName, "r")
        return file.read()
    except OSError:
        print("File not found!")

def splitFile(sourceFile):
    return sourceFile.replace(",", "").split("\n")

def createOutputFile(fileName):
    try:
        return open(str(fileName), "wb") # Always cast input to string before I get stupid errors
    except OSError as e:
        print("I cannot make the output bin file :( Error: {e}") # The raw error should only be printed when verbose mode is set but that requires making the argument parser and that is something for a later date

def removeComments(splitLines, lineCount):
    indexOfComment = splitLines.index(';')
    
    print(f"I've found a comment the idx of the comment in the array is at {indexOfComment} the array is {splitLines}") # This should only be printed in verbose mode lowk
    
    if indexOfComment != 0:
        return splitLines[:indexOfComment]
    else:
        lineCount -= 1
        return
    
    # I may have written this poorly when refactoring this piece of code, I need to do some good testing with comments to check if this bullshit is still working

def writeInstructionsToFile(splitLines, fileHandler, lineCount):
    if splitLines[0] in fileHandler.instructionDict:
        if len(fileHandler.instructionDict[splitLines[0]]["args"]) == 0: # When there are no arguments to be parsed into the opcode just run the function without parsing anything 
            fileHandler.instructionDict[splitLines[0]]["handler"]()
        else:
            fileHandler.instructionDict[splitLines[0]]["handler"](splitLines[1:]) # When the opcode needs some additional arguments parse them into the function as a list so the functions itself can decide if it only needs one or 500
    elif splitLines[0] == "\0" or splitLines[0] == "\n" or splitLines[0] == "":
        print(f"Found a newline or a null terminator? Wattafak (I should ignore this and not give an error but it is fun) line: {lineCount}")
    else:
        print(f"You made a mistake in the code! Something whent wrong with this line: {lineCount}")

def assemble(sourceFile): # Make this function more true to its name, this function has to many things it is supposed to be doing (and is actually doing)

    # All these mappings are defined in the spec (../docs/specification.md)

    sourceFile = splitFile(sourceFile)

    outputFile = createOutputFile("bin.mabin") # The name of the program should also be something that the user can choose using a command line argument but again that requires writing the argument parser

    lineCount = 0 # This is so if there is an error I can say what line the error is on
    
    fileHandler = instructionFuncs.binFileWriter(outputFile)

    for items in sourceFile:
        splitLines = items.split(" ")
        lineCount += 1

        if ';' in splitLines: # removeComments should obv only be ran when I detect comments it should not be detecting and when detected remove comments (tho having a general preprocessor stage eventually will be nice)
            splitLines = removeComments(splitLines, lineCount)

        writeInstructionsToFile(splitLines, fileHandler, lineCount)
    

if __name__ == "__main__":
    try:
        userGivenFileName = sys.argv[1] # Maybe check if the user passed a verbose flag so to log things into the terminal
    except:
        print("You did not provide any file! Usage: python3 assembler.py `filelocation.mav`") 
        exit(-1)

    if readFile(userGivenFileName) is not None:
        assemble(readFile(userGivenFileName))